version: '3'
services:
  strapi:
    image: strapi/strapi
    restart: unless-stopped
    env_file: .env
    environment:
      APP_NAME: strapi-app
      DATABASE_CLIENT: mongo
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'